apiVersion: v1
kind: Service
metadata:
  name: chain-client-evm-op-server-614
  namespace: "{{.Deployment.Namespace}}"
spec:
  selector:
    app: chain-client-evm-op-614
  type: ClusterIP
  ports:
    - protocol: TCP
      name: chain-client-evm-op-api-614
      port: 9100
      targetPort: 9100
---
# Source: chain-client-evm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-client-evm-op-614
  namespace: "{{.Deployment.Namespace}}"
  labels:
    app: chain-client-evm-op-614
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain-client-evm-op-614
  template:
    metadata:
      labels:
        app: chain-client-evm-op-614
    spec:
      containers:
        - name: chain-client-evm-op-614
          image: "{{.Deployment.Image}}"
          ports:
            - containerPort: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}9100{{ end }}
          env:
            - name: CLEAR_PADDING
              value: 'true'
            - name: "STATUS_KEY"
              value: "chain-client-status-report-{{.Deployment.Name}}"
            - name: CHAIN_TYPE
              value: "evm"
            {{range .Deployment.CustomEnv}}
            - name: "{{.Key}}"
              value: "{{.Value}}"
            {{end}}
            - name: REDIS_PASSWORD
              value: "{{.Deployment.RedisPass}}"
            - name: EVM_CLIENT_PORT
              value: "9100"
            - name: REDIS_HOST
              value: "{{.Deployment.RedisHost}}"
            - name: REDIS_PORT
              value: "{{.Deployment.RedisPort}}"
            - name: SYSTEM_CHAIN_ID
              value: "614"
            - name: CHAIN_ID
              value: "10"
            - name: OS_API_KEY
              value: "{{.Deployment.OsApiKey}}"
            - name: OS_API_SECRET
              value: "{{.Deployment.OsApiSecret}}"
            - name: OS_SYSTEM_SERVER
              value: "{{.Deployment.OsSystemServer}}"
            - name: CONTRACT_ADDRESS
              value: "0x6F12FED6Cd5BeBFA3351c447f7873B76178B1b84"
            - name: START_BLOCK
              value: "{{ if .Deployment.StartBlock }}{{.Deployment.StartBlock}}{{ else }}119733829{{ end }}"
            - name: RPC_URL
              value: "{{ if .Deployment.RpcUrl }}{{.Deployment.RpcUrl}}{{ else }}https://mainnet.optimism.io{{ end }}"
            - name: START_TOP_HEIGHT
              value: "true"
            - name: AUTO_START
              value: "false"
            - name: USE_DOTNET
              value: "false"
            - name: AUTO_RPC
              value: "false"
            - name: LOG_LEVEL
              value: "1"
            - name: PROJECT_EXPANSION
              value: "true"
            - name: MONGODB_HOST
              value: "{{.Deployment.MongodbHost}}"
            - name: MONGODB_ACCOUNT
              value: "{{.Deployment.MongodbAccount}}"
            - name: MONGODB_PASSWORD
              value: "{{.Deployment.MongodbPass}}"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DBNAME_LP_STORE
              value: "{{.Deployment.MongodbDbnameLpStore}}"