apiVersion: v1
kind: Service
metadata:
  name: "amm-market-{{.Deployment.Name}}-service"
  namespace: "{{.Deployment.Namespace}}"
spec:
  selector:
    app: "amm-market-{{.Deployment.Name}}"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "amm-market-{{.Deployment.Name}}-service"
      port: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
      targetPort: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "amm-market-{{.Deployment.Name}}"
  namespace: "{{.Deployment.Namespace}}"
  labels:
    app: "amm-market-{{.Deployment.Name}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "amm-market-{{.Deployment.Name}}"
  template:
    metadata:
      labels:
        app: "amm-market-{{.Deployment.Name}}"
    spec:
      containers:
        - name: "amm-market-{{.Deployment.Name}}"
          image: "{{.Deployment.Image}}"
          command:
            - python3
            - ./app.py
          workingDir: /app
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 512Mi
          ports:
            - containerPort: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
          env:
            - name: "STATUS_KEY"
              value: "amm-market-status-report-{{.Deployment.Name}}"
            - name: REDIS_HOST
              value: "{{.Deployment.RedisHost}}"
            - name: REDIS_PORT
              value: "{{.Deployment.RedisPort}}"
            - name: REDIS_PASSWORD
              value: "{{.Deployment.RedisPass}}"
            {{range .Deployment.CustomEnv}}
            - name: "{{.Key}}"
              value: "{{.Value}}"
            {{end}}
            - name: "SERVICE_PORT"
              value: "{{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}"
            - name: MONGODB_HOST
              value: "{{.Deployment.MongodbHost}}"
            - name: MONGODB_PORT
              value: "{{.Deployment.MongodbPort}}"
            - name: MONGODB_ACCOUNT
              value: "{{.Deployment.MongodbAccount}}"
            - name: MONGODB_PASS
              value: "{{.Deployment.MongodbPass}}"
            - name: MONGODB_DBNAME_LP_STORE
              value: "{{.Deployment.MongodbDbnameLpStore}}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace

        - name: "amm-market-{{.Deployment.Name}}-ccxt"
          image: "{{.Deployment.Image}}"
          command:
            - ts-node
            - ./src/App.ts
          workingDir: /app/otmoic-ccxt-market
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 600Mi
          env:
            - name: "STATUS_KEY"
              value: "amm-market-status-report-{{.Deployment.Name}}"
            - name: REDIS_HOST
              value: "{{.Deployment.RedisHost}}"
            - name: REDIS_PORT
              value: "{{.Deployment.RedisPort}}"
            - name: REDIS_PASSWORD
              value: "{{.Deployment.RedisPass}}"
            - name: "SERVICE_PORT"
              value: "{{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}"
            - name: MONGODB_HOST
              value: "{{.Deployment.MongodbHost}}"
            - name: MONGODB_PORT
              value: "{{.Deployment.MongodbPort}}"
            - name: MONGODB_ACCOUNT
              value: "{{.Deployment.MongodbAccount}}"
            - name: MONGODB_PASSWORD
              value: "{{.Deployment.MongodbPass}}"
            - name: MONGODB_DBNAME_LP_STORE
              value: "{{.Deployment.MongodbDbnameLpStore}}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace